
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Operaciones.OperacionesAritméticas;
import javax.swing.JOptionPane;
/**
 *
 * @author jose eduardo ramirez
 */
public class calcu extends javax.swing.JFrame {
    OperacionesAritméticas operacion=new OperacionesAritméticas();

    /**
     * Creates new form calcu
     */
    public calcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        resultado1 = new javax.swing.JLabel();
        numero1 = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        sumar = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("primer numero:");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("segundo nuemero:");

        resultado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        resultado.setForeground(new java.awt.Color(0, 255, 0));

        resultado1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        resultado1.setForeground(new java.awt.Color(255, 204, 255));

        numero1.setBackground(new java.awt.Color(0, 0, 0));
        numero1.setForeground(new java.awt.Color(255, 255, 255));
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        numero2.setBackground(new java.awt.Color(0, 0, 0));
        numero2.setForeground(new java.awt.Color(255, 255, 255));
        numero2.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));

        sumar.setForeground(java.awt.Color.cyan);
        sumar.setText("sumar");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });

        resta.setForeground(new java.awt.Color(255, 0, 0));
        resta.setText("resta");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        multiplicar.setForeground(new java.awt.Color(153, 102, 255));
        multiplicar.setText("multiplicar");
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        dividir.setForeground(new java.awt.Color(255, 255, 0));
        dividir.setText("dividir");
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numero1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(numero2))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sumar)
                                        .addGap(18, 18, 18)
                                        .addComponent(resta))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(multiplicar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dividir))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumar)
                    .addComponent(resta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicar)
                    .addComponent(dividir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultado)
                .addGap(31, 31, 31)
                .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        String numero1=this.numero1.getText();
        String numero2=this.numero2.getText();
        if(this.numero1.getText().equals("") && this.numero2.getText().equals("")){
            numero1="0";
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla y sengunda casilla ");
        }else if(this.numero1.getText().equals("") && this.numero2.getText() != null){
            numero1="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla ");

        }else if(this.numero1.getText() != null && this.numero2.getText().equals("")){
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la segunda casilla ");
        }
        this.resultado.setText(operacion.multiplicacion(numero1, numero2));
    }//GEN-LAST:event_multiplicarActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        String numero1=this.numero1.getText();
        String numero2=this.numero2.getText();
        if(this.numero1.getText().equals("") && this.numero2.getText().equals("")){
            numero1="0";
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla y sengunda casilla ");
        }else if(this.numero1.getText().equals("") && this.numero2.getText() != null){
            numero1="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla ");

        }else if(this.numero1.getText() != null && this.numero2.getText().equals("")){
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la segunda casilla ");
        }
        this.resultado.setText(operacion.resta(numero1, numero2));
    }//GEN-LAST:event_restaActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        String numero1=this.numero1.getText();
        String numero2=this.numero2.getText();
        if(this.numero1.getText().equals("") && this.numero2.getText().equals("")){
            numero1="0";
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla y sengunda casilla ");
        }else if(this.numero1.getText().equals("") && this.numero2.getText() != null){
            numero1="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla ");

        }else if(this.numero1.getText() != null && this.numero2.getText().equals("")){
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la segunda casilla ");
        }
        this.resultado.setText(operacion.suma(numero1, numero2));

    }//GEN-LAST:event_sumarActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero1ActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        String numero1=this.numero1.getText();
        String numero2=this.numero2.getText();
        if(this.numero1.getText().equals("") && this.numero2.getText().equals("")){
            numero1="0";
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla y sengunda casilla ");
        }else if(this.numero1.getText().equals("") && this.numero2.getText() != null){
            numero1="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la primer casilla ");

        }else if(this.numero1.getText() != null && this.numero2.getText().equals("")){
            numero2="0";
            JOptionPane.showMessageDialog(null, "no ha ingresado nada en la segunda casilla ");
        }
        this.resultado.setText(operacion.division(numero1, numero2));
    }//GEN-LAST:event_dividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dividir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton multiplicar;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JButton resta;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultado1;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
